window.LEDGER_DATA = {
  "meta": {
    "version": 1,
    "siteTitle": "球哥的足球账本",
    "subtitle": "为热爱买单，每一笔都值得记录",
    "updatedAt": "2026-08-20"
  },
  "records": [
    {
      "id": "s-live-1",
      "type": "live",
      "date": "2023-07-21",
      "home": "上海海港",
      "away": "沧州雄狮",
      "venue": "",
      "result": "3 : 0",
      "price": 180,
      "note": "",
      "photo": "",
      "homeLogo": "assets/live/logos/2025/shanghai-port-v2021.svg",
      "awayLogo": "assets/live/logos/2023/cangzhou-mighty-lions-v2021.svg"
    },
    {
      "id": "s-live-2",
      "type": "live",
      "date": "2025-02-23",
      "home": "上海海港",
      "away": "深圳",
      "venue": "",
      "result": "3 : 1",
      "price": 140,
      "note": "",
      "photo": "assets/live/2025-02-23_port_vs_shenzhen.jpg",
      "homeLogo": "assets/live/logos/2025/shanghai-port-v2021.svg",
      "awayLogo": "assets/live/logos/2025/shenzhen-peng-city-v2024.svg"
    },
    {
      "id": "s-live-3",
      "type": "live",
      "date": "2025-03-01",
      "home": "上海申花",
      "away": "北京国安",
      "venue": "",
      "result": "2 : 2",
      "price": 320,
      "note": "",
      "photo": "assets/live/2025-03-01_shenhua_vs_guoan.jpg",
      "homeLogo": "assets/live/logos/2025/shanghai-shenhua-v2022.svg",
      "awayLogo": "assets/live/logos/2025/beijing-guoan-v2022.svg"
    },
    {
      "id": "s-live-4",
      "type": "live",
      "date": "2025-04-12",
      "home": "上海申花",
      "away": "浙江队",
      "venue": "",
      "result": "3 : 2",
      "price": 260,
      "note": "",
      "photo": "assets/live/2025-04-12_shenhua_vs_zhejiang.jpg",
      "homeLogo": "assets/live/logos/2025/shanghai-shenhua-v2022.svg",
      "awayLogo": "assets/live/logos/2025/zhejiang-professional-v2022.svg"
    },
    {
      "id": "s-live-5",
      "type": "live",
      "date": "2025-04-20",
      "home": "上海海港",
      "away": "成都蓉城",
      "venue": "",
      "result": "1 : 3",
      "price": 140,
      "note": "",
      "photo": "assets/live/2025-04-20_port_vs_rongcheng.jpg",
      "homeLogo": "assets/live/logos/2025/shanghai-port-v2021.svg",
      "awayLogo": "assets/live/logos/2025/chengdu-rongcheng-v2021.svg"
    },
    {
      "id": "s-live-6",
      "type": "live",
      "date": "2025-05-01",
      "home": "浙江队",
      "away": "长春亚泰",
      "venue": "",
      "result": "4 : 2",
      "price": 180,
      "note": "",
      "photo": "assets/live/2025-05-01_zhejiang_vs_yatai.jpg",
      "homeLogo": "assets/live/logos/2025/zhejiang-professional-v2022.svg",
      "awayLogo": "assets/live/logos/2025/changchun-yatai-v2007.svg"
    },
    {
      "id": "s-live-7",
      "type": "live",
      "date": "2025-05-17",
      "home": "上海海港",
      "away": "山东泰山",
      "venue": "",
      "result": "1 : 1",
      "price": 230,
      "note": "",
      "photo": "",
      "homeLogo": "assets/live/logos/2025/shanghai-port-v2021.svg",
      "awayLogo": "assets/live/logos/2025/shandong-taishan-v2022.svg"
    },
    {
      "id": "s-live-8",
      "type": "live",
      "date": "2025-06-22",
      "home": "上海海港",
      "away": "上海申花",
      "venue": "",
      "result": "2 : 3",
      "price": 230,
      "note": "足协杯",
      "photo": "assets/live/2025-06-22_port_vs_shenhua.jpg",
      "homeLogo": "assets/live/logos/2025/shanghai-port-v2021.svg",
      "awayLogo": "assets/live/logos/2025/shanghai-shenhua-v2022.svg"
    },
    {
      "id": "s-live-9",
      "type": "live",
      "date": "2025-08-09",
      "home": "上海申花",
      "away": "上海海港",
      "venue": "",
      "result": "1 : 2",
      "price": 320,
      "note": "",
      "photo": "assets/live/2025-08-09_shenhua_vs_port.jpg",
      "homeLogo": "assets/live/logos/2025/shanghai-shenhua-v2022.svg",
      "awayLogo": "assets/live/logos/2025/shanghai-port-v2021.svg"
    },
    {
      "id": "s-live-10",
      "type": "live",
      "date": "2025-08-10",
      "home": "浙江队",
      "away": "北京国安",
      "venue": "",
      "result": "3 : 4",
      "price": 220,
      "note": "",
      "photo": "assets/live/2025-08-10_zhejiang_vs_guoan.jpg",
      "homeLogo": "assets/live/logos/2025/zhejiang-professional-v2022.svg",
      "awayLogo": "assets/live/logos/2025/beijing-guoan-v2022.svg"
    },
    {
      "id": "s-live-11",
      "type": "live",
      "date": "2025-08-16",
      "home": "浙江队",
      "away": "上海申花",
      "venue": "",
      "result": "0 : 0",
      "price": 180,
      "note": "",
      "photo": "assets/live/2025-08-16_zhejiang_vs_shenhua.jpg",
      "homeLogo": "assets/live/logos/2025/zhejiang-professional-v2022.svg",
      "awayLogo": "assets/live/logos/2025/shanghai-shenhua-v2022.svg"
    },
    {
      "id": "s-live-12",
      "type": "live",
      "date": "2025-09-12",
      "home": "上海申花",
      "away": "山东泰山",
      "venue": "",
      "result": "3 : 3",
      "price": 260,
      "note": "",
      "photo": "assets/live/2025-09-12_shenhua_vs_taishan.jpg",
      "homeLogo": "assets/live/logos/2025/shanghai-shenhua-v2022.svg",
      "awayLogo": "assets/live/logos/2025/shandong-taishan-v2022.svg"
    },
    {
      "id": "s-live-13",
      "type": "live",
      "date": "2025-09-21",
      "home": "上海申花",
      "away": "成都蓉城",
      "venue": "",
      "result": "1 : 1",
      "price": 260,
      "note": "",
      "photo": "assets/live/2025-09-21_shenhua_vs_rongcheng.jpg",
      "homeLogo": "assets/live/logos/2025/shanghai-shenhua-v2022.svg",
      "awayLogo": "assets/live/logos/2025/chengdu-rongcheng-v2021.svg"
    },
    {
      "id": "s-live-14",
      "type": "live",
      "date": "2025-10-31",
      "home": "上海海港",
      "away": "浙江队",
      "venue": "",
      "result": "3 : 0",
      "price": 140,
      "note": "",
      "photo": "assets/live/2025-10-31_port_vs_zhejiang.jpg",
      "homeLogo": "assets/live/logos/2025/shanghai-port-v2021.svg",
      "awayLogo": "assets/live/logos/2025/zhejiang-professional-v2022.svg"
    },
    {
      "id": "s-live-15",
      "type": "live",
      "date": "2026-03-14",
      "home": "浙江队",
      "away": "上海申花",
      "venue": "",
      "result": "1 : 1",
      "price": 220,
      "note": "",
      "photo": "assets/live/2026-03-14_zhejiang_vs_shenhua.jpg",
      "homeLogo": "assets/live/logos/2026/zhejiang-professional-v2022.svg",
      "awayLogo": "assets/live/logos/2026/shanghai-shenhua-v2022.svg"
    },
    {
      "id": "s-live-16",
      "type": "live",
      "date": "2026-04-11",
      "home": "上海申花",
      "away": "上海海港",
      "venue": "",
      "result": "1 : 0",
      "price": 320,
      "note": "",
      "photo": "assets/live/2026-04-11_shenhua_vs_port.jpg",
      "homeLogo": "assets/live/logos/2026/shanghai-shenhua-v2022.svg",
      "awayLogo": "assets/live/logos/2026/shanghai-port-v2021.svg"
    },
    {
      "id": "s-live-17",
      "type": "live",
      "date": "2026-04-25",
      "home": "上海海港",
      "away": "武汉三镇",
      "venue": "",
      "result": "4 : 0",
      "price": 140,
      "note": "",
      "photo": "assets/live/2026-04-25_port_vs_wuhan.jpg",
      "homeLogo": "assets/live/logos/2026/shanghai-port-v2021.svg",
      "awayLogo": "assets/live/logos/2026/wuhan-three-towns-v2019.svg"
    },
    {
      "id": "s-live-18",
      "type": "live",
      "date": "2026-05-09",
      "home": "上海申花",
      "away": "重庆",
      "venue": "",
      "result": "2 : 2",
      "price": 150,
      "note": "",
      "photo": "assets/live/2026-05-09_shenhua_vs_chongqing.jpg",
      "homeLogo": "assets/live/logos/2026/shanghai-shenhua-v2022.svg",
      "awayLogo": "assets/live/logos/2026/chongqing-tonglianglong-v2023.svg"
    },
    {
      "id": "s-live-19",
      "type": "live",
      "date": "2026-05-15",
      "home": "上海海港",
      "away": "浙江队",
      "venue": "",
      "result": "2 : 2",
      "price": 80,
      "note": "",
      "photo": "assets/live/2026-05-15_port_vs_zhejiang.jpg",
      "homeLogo": "assets/live/logos/2026/shanghai-port-v2021.svg",
      "awayLogo": "assets/live/logos/2026/zhejiang-professional-v2022.svg"
    },
    {
      "id": "s-live-20",
      "type": "live",
      "date": "2026-07-05",
      "home": "上海申花",
      "away": "浙江队",
      "venue": "",
      "result": "3 : 2",
      "price": 150,
      "note": "",
      "photo": "assets/live/2026-07-05_shenhua_vs_zhejiang.jpg",
      "homeLogo": "assets/live/logos/2026/shanghai-shenhua-v2022.svg",
      "awayLogo": "assets/live/logos/2026/zhejiang-professional-v2022.svg"
    },
    {
      "id": "s-live-21",
      "type": "live",
      "date": "2026-07-25",
      "home": "上海海港",
      "away": "上海申花",
      "venue": "",
      "result": "2 : 0",
      "price": 330,
      "note": "",
      "photo": "assets/live/2026-07-25_port_vs_shenhua.jpg",
      "homeLogo": "assets/live/logos/2026/shanghai-port-v2021.svg",
      "awayLogo": "assets/live/logos/2026/shanghai-shenhua-v2022.svg"
    },
    {
      "id": "s-live-22",
      "type": "live",
      "date": "2026-08-15",
      "home": "上海申花",
      "away": "河南",
      "venue": "",
      "result": "4 : 1",
      "price": 200,
      "note": "",
      "photo": "assets/live/2026-08-15_shenhua_vs_henan.jpg",
      "homeLogo": "assets/live/logos/2026/shanghai-shenhua-v2022.svg",
      "awayLogo": "assets/live/logos/2026/henan-fc-v2023.svg"
    },
    {
      "id": "s-jersey-1",
      "type": "jersey",
      "date": "2025-02-16",
      "team": "切尔西",
      "teamKind": "俱乐部",
      "season": "2024/25",
      "jerseyType": "主场",
      "version": "球迷版",
      "hasPrinting": "是",
      "competition": "",
      "number": "",
      "player": "",
      "price": 699,
      "note": "短袖+印号",
      "teamLogo": "assets/jersey/logos/chelsea-fc-v2006.svg",
      "photo": "assets/jersey/chelsea_2024-25_home.jpg"
    },
    {
      "id": "s-jersey-2",
      "type": "jersey",
      "date": "2025-06-22",
      "team": "阿森纳",
      "teamKind": "俱乐部",
      "season": "2025/26",
      "jerseyType": "主场",
      "version": "球迷版",
      "hasPrinting": "是",
      "competition": "",
      "number": "",
      "player": "",
      "price": 849,
      "note": "短袖+印号",
      "teamLogo": "assets/jersey/logos/arsenal-fc-v2002.svg",
      "photo": ""
    },
    {
      "id": "s-jersey-3",
      "type": "jersey",
      "date": "2025-10-24",
      "team": "切尔西",
      "teamKind": "俱乐部",
      "season": "2025/26",
      "jerseyType": "主场",
      "version": "球员版",
      "hasPrinting": "否",
      "competition": "",
      "number": "",
      "player": "",
      "price": 759,
      "note": "短袖",
      "teamLogo": "assets/jersey/logos/chelsea-fc-v2006.svg",
      "photo": "assets/jersey/chelsea_2025-26_home.jpg"
    },
    {
      "id": "s-jersey-4",
      "type": "jersey",
      "date": "2026-01-11",
      "team": "德国队",
      "teamKind": "国家队",
      "season": "2026",
      "jerseyType": "主场",
      "version": "球迷版",
      "hasPrinting": "是",
      "competition": "",
      "number": "",
      "player": "",
      "price": 849,
      "note": "短袖+印号",
      "teamLogo": "assets/jersey/logos/germany-national-team-v2021.svg",
      "photo": "assets/jersey/germany_2026_home.jpg"
    },
    {
      "id": "s-jersey-5",
      "type": "jersey",
      "date": "2026-02-07",
      "team": "浙江队",
      "teamKind": "俱乐部",
      "season": "2025/26",
      "jerseyType": "主场",
      "version": "球迷版",
      "hasPrinting": "否",
      "competition": "",
      "number": "",
      "player": "",
      "price": 529,
      "note": "短袖",
      "teamLogo": "assets/live/logos/2025/zhejiang-professional-v2022.svg",
      "photo": "assets/jersey/zhejiang_2026_home.jpg"
    },
    {
      "id": "s-jersey-6",
      "type": "jersey",
      "date": "2026-05-15",
      "team": "意大利",
      "teamKind": "国家队",
      "season": "2026",
      "jerseyType": "客场",
      "version": "球迷版",
      "hasPrinting": "否",
      "competition": "",
      "number": "",
      "player": "",
      "price": 271.4,
      "note": "短袖",
      "photo": "assets/jersey/italy_2026_away.jpg"
    },
    {
      "id": "s-jersey-7",
      "type": "jersey",
      "date": "2026-06-16",
      "team": "阿根廷",
      "teamKind": "国家队",
      "season": "2026",
      "jerseyType": "客场",
      "version": "球员版",
      "hasPrinting": "否",
      "competition": "",
      "number": "",
      "player": "",
      "price": 999,
      "note": "短袖",
      "teamLogo": "assets/jersey/logos/argentina-national-team-v2024.svg",
      "photo": "assets/jersey/argentina_2026_away.jpg"
    },
  ]
};
